name: Release
on:
  workflow_dispatch: # Only manual trigger and only for the main branch
    branches:
      - main
    inputs:
      bump_level:
        type: choice
        description: Select bump level
        required: true
        options:
          - patch
          - minor
          - major
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN_GITHUB }}

    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 - --version 1.2.2

    - name: Build and publish
      run: |
        BUMP_LEVEL=${{ github.event.inputs.bump_level }}
        echo "bump level: ${BUMP_LEVEL}"

        NEW_VERSION=$(poetry version -s "${BUMP_LEVEL}")
        git config --local user.email "Bumpversion"
        git config --local user.name "Bumpversion"
        echo "new version: ${NEW_VERSION}"
        poetry update
        git add pyproject.toml poetry.lock
        git commit -m "Bump version to ${NEW_VERSION}"
        git tag "v${NEW_VERSION}"

        git push
        git push --tags
        echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      with:
        tag_name: v${{ env.NEW_VERSION }}
        release_name: v${{ env.NEW_VERSION }}
        body: |
          https://github.com/ffinfo/delta-sync/releases/tag/v${{ env.NEW_VERSION }}
        draft: false
        prerelease: false